import { describe, it } from 'node:test'
import assert from 'node:assert/strict'

import { portOverride } from './port-override.ts'
import type { ResolvedCompose, ResolvedService } from './compose.ts'

const HEADER = '# Written by hostd. The port is set in the portal; do not edit this file.\nservices:\n'
const compose = (services: Record<string, ResolvedService>): ResolvedCompose => ({ name: 'acme', services })

describe('portOverride', () => {
    it('replaces a hard-coded mapping with the chosen port on loopback', () => {
        const result = portOverride(compose({ web: { build: '.', ports: [{ target: 3000, published: '3000', protocol: 'tcp' }] } }), 'WEB_PORT')
        assert.deepEqual(result, {
            ok: true, service: 'web', target: 3000,
            text: `${HEADER}  "web":\n    ports: !override ["127.0.0.1:\${WEB_PORT}:3000"]\n`,
        })
    })

    // backroom's "${BIND_ADDR:-127.0.0.1}:${PORT:-3001}:${PORT:-3001}", as config resolves it
    it('keeps the container port the repo resolves to', () => {
        const result = portOverride(compose({ backroom: { build: '.', ports: [{ target: 3001, published: '3001', host_ip: '127.0.0.1', protocol: 'tcp' }] } }), 'WEB_PORT')
        assert.equal(result.ok && result.service, 'backroom')
        assert.equal(result.ok && result.target, 3001)
    })

    it('names the registry\'s own port variable', () => {
        const result = portOverride(compose({ web: { ports: [{ target: 3000 }] } }), 'PORT')
        assert.match(result.ok ? result.text : '', /"127\.0\.0\.1:\$\{PORT\}:3000"/)
    })

    it('uses expose when the service publishes nothing', () => {
        const result = portOverride(compose({ web: { build: '.', expose: ['8080'] } }), 'WEB_PORT')
        assert.equal(result.ok && result.target, 8080)
    })

    it('skips a UDP entry listed before the TCP one', () => {
        const result = portOverride(compose({ web: { ports: [{ target: 9000, published: '9000', protocol: 'udp' }, { target: 3000, published: '3000', protocol: 'tcp' }] } }), 'WEB_PORT')
        assert.equal(result.ok && result.target, 3000)
    })

    it('refuses a site service that names no port', () => {
        assert.deepEqual(portOverride(compose({ web: { build: '.' } }), 'WEB_PORT'), {
            ok: false,
            problem: 'web does not say which port it listens on; add expose: ["3000"] (the port inside the container) to it in the compose file',
        })
    })

    it('refuses a site service on the host network', () => {
        assert.deepEqual(portOverride(compose({ web: { network_mode: 'host', expose: ['3000'] } }), 'WEB_PORT'), {
            ok: false, problem: 'web uses network_mode: host, so hostd cannot choose its port; remove network_mode from it',
        })
    })

    it('picks the one site service that says its port, and leaves a portless one out', () => {
        const result = portOverride(compose({ web: { ports: [{ target: 3000 }] }, worker: { build: '.' } }), 'WEB_PORT')
        assert.equal(result.ok && result.service, 'web')
        assert.doesNotMatch(result.ok ? result.text : '', /worker/)
    })

    it('refuses when it cannot tell which service is the site', () => {
        assert.deepEqual(portOverride(compose({ web: { build: '.' }, worker: { build: '.' } }), 'WEB_PORT'), {
            ok: false,
            problem: 'hostd cannot tell which service is the site (web, worker); give the others an image it recognises as a database, or publish a port from the site\'s service only',
        })
    })

    it('refuses a compose file with no services', () => {
        assert.deepEqual(portOverride(compose({}), 'WEB_PORT'), { ok: false, problem: 'the compose file declares no services' })
    })

    // A database published to the host would be open on the dedi's public interface, since Docker's own
    // iptables rules go around the firewall, and two sites publishing 27017 would collide
    it('strips host ports from every other service', () => {
        const result = portOverride(compose({
            web: { ports: [{ target: 3000 }] },
            db: { image: 'mongo:7', ports: [{ target: 27017, published: '27017' }] },
        }), 'WEB_PORT')
        assert.equal(result.ok && result.text,
            `${HEADER}  "db":\n    ports: !reset []\n  "web":\n    ports: !override ["127.0.0.1:\${WEB_PORT}:3000"]\n`)
    })
})
