// The compose override that makes the portal's port the only host port a site publishes, whatever the
// repo's own compose file says. The repo is never edited: a deploy checks out a fresh tree and the
// checkout's copy of a file always wins, so an edit would last until the next deploy. Instead hostd owns
// one more compose file, listed last, which compose merges over the repo's:
//
// - the site's service gets `ports: !override`, so the repo's own mappings, a hard-coded "3000:3000"
//   included, cannot also claim a host port; always on loopback, since Apache is the only thing that
//   should reach a site
// - every other service with ports gets `ports: !reset []`, so a database the repo publishes for a
//   developer's laptop is not open on the dedi (Docker's iptables rules go around the firewall)
//
// Services still reach each other over the compose network by service name, so nothing inside a site
// changes. The port itself stays in .env: the file names the variable, never the number.

import { posix } from 'node:path'

import { PORT_OVERRIDE_FILE } from '../shared/registry.ts'
import { guessRole, resolveCompose, type ComposeLocation, type ResolvedCompose, type ResolvedService, type Runner } from './compose.ts'

export type PortOverride = { ok: true, text: string, service: string, target: number } | { ok: false, problem: string }

// One port, as config writes a target or an expose entry: a number, or a string that may carry a
// protocol ("3000/tcp"). A range ("3000-3005") is not one port and is skipped.
function singlePort(value: string | number | undefined): number | null {
    const text = typeof value === 'number' ? String(value) : value?.trim()
    const match = text === undefined ? null : /^(\d{1,5})(?:\/tcp)?$/.exec(text)
    if (!match) return null
    const port = Number(match[1])
    return port >= 1 && port <= 65535 ? port : null
}

// The first TCP target in the order the file lists them, then the first expose entry
function containerPort(service: ResolvedService): number | null {
    for (const port of service.ports ?? []) {
        if (port.protocol !== undefined && port.protocol !== 'tcp') continue
        const target = singlePort(port.target)
        if (target !== null) return target
    }
    for (const entry of service.expose ?? []) {
        const port = singlePort(entry)
        if (port !== null) return port
    }
    return null
}

const saysItsPort = (service: ResolvedService) => (service.ports?.length ?? 0) > 0 || (service.expose?.length ?? 0) > 0

export function portOverride(resolved: ResolvedCompose, portEnv: string): PortOverride {
    // Sorted, so the file is the same text for the same services however config ordered them
    const names = Object.keys(resolved.services).sort()
    if (names.length === 0) return { ok: false, problem: 'the compose file declares no services' }
    const sites = names.filter(name => guessRole(resolved.services[name]!).role === 'site')
    // A lone site service is the site even when it names no port, so the refusal below can say what to add
    const candidates = sites.length === 1 ? sites : sites.filter(name => saysItsPort(resolved.services[name]!))
    if (candidates.length !== 1) {
        return {
            ok: false,
            problem: `hostd cannot tell which service is the site (${(sites.length > 0 ? sites : names).join(', ')}); give the others an image it recognises as a database, or publish a port from the site's service only`,
        }
    }
    const service = candidates[0]!
    const web = resolved.services[service]!
    if (web.network_mode === 'host') {
        return { ok: false, problem: `${service} uses network_mode: host, so hostd cannot choose its port; remove network_mode from it` }
    }
    const target = containerPort(web)
    if (target === null) {
        return { ok: false, problem: `${service} does not say which port it listens on; add expose: ["3000"] (the port inside the container) to it in the compose file` }
    }

    // Built as text: the yaml library would need teaching to write the two tags. JSON strings are valid
    // YAML double-quoted scalars, so a service name or a mapping can never break out of its line.
    const lines = ['# Written by hostd. The port is set in the portal; do not edit this file.', 'services:']
    for (const name of names) {
        if (name === service) {
            lines.push(`  ${JSON.stringify(name)}:`, `    ports: !override [${JSON.stringify(`127.0.0.1:\${${portEnv}}:${target}`)}]`)
        } else if ((resolved.services[name]!.ports?.length ?? 0) > 0) {
            lines.push(`  ${JSON.stringify(name)}:`, '    ports: !reset []')
        }
    }
    return { ok: true, text: `${lines.join('\n')}\n`, service, target }
}

export type PortOverrideResult = { ok: true, composePaths: string[], service: string, target: number } | { ok: false, problem: string }

export function isPortOverride(path: string): boolean {
    return posix.basename(path) === PORT_OVERRIDE_FILE
}

export function portOverridePath(dir: string): string {
    return posix.join(dir, PORT_OVERRIDE_FILE)
}

// Resolves the repo's own files, never the override itself (it would hide the mappings being replaced),
// so this is the same answer the first time and every time after. Run after the port is in .env, so any
// ${...} in the repo's mappings resolves to what the repo would run with. Answers the environment's full
// compose list with the override last, which is what the registry records and compose is run with.
export async function buildPortOverride(
    location: ComposeLocation, portEnv: string, run: Runner, writeFile: (path: string, text: string) => Promise<void>,
): Promise<PortOverrideResult> {
    const own = location.composePaths.filter(path => !isPortOverride(path))
    if (own.length === 0) return { ok: false, problem: 'the environment names no compose file of its own' }
    const resolved = await resolveCompose({ dir: location.dir, composePaths: own }, run)
    if (!resolved.ok) return resolved
    const override = portOverride(resolved.resolved, portEnv)
    if (!override.ok) return override
    const path = portOverridePath(location.dir)
    await writeFile(path, override.text)
    return { ok: true, composePaths: [...own, path], service: override.service, target: override.target }
}
