// One environment's Apache vhost, rendered from a fixed template. The only values that reach the output
// are ones the caller has already validated: hostnames through normaliseHostname, the port and the id
// from the registry entry, the token from api, and the certificate paths from the agent's own
// configuration. Nothing here escapes anything, because nothing here is allowed to receive a value that
// would need escaping.

import { posix } from 'node:path'
import type { EnvironmentName } from '../shared/registry.ts'

export type VhostInput = {
    id: string
    environment: EnvironmentName
    primary: string
    aliases: string[]
    port: number
    token: string
    certificate: { chain: string, key: string }
    maintenanceDir: string
    maintenanceFlag: string
    acmeWebroot: string
}

export function vhostPath(dir: string, id: string, environment: EnvironmentName): string {
    return posix.join(dir, `${id}-${environment}.conf`)
}

const aliasLines = (aliases: string[]): string =>
    aliases.map(alias => `    ServerAlias ${alias}`).join('\n')

// Port 80 exists to do three things and nothing else: answer the ACME challenge (which 4b needs and which
// costs nothing to serve now), answer the verification token, and send everything else to https. The
// challenge and the token are matched before the rewrite, because a 301 would take a challenge with it.
function port80(input: VhostInput): string {
    return `<VirtualHost *:80>
    ServerName ${input.primary}
${aliasLines(input.aliases)}

    Alias "/.well-known/acme-challenge" "${input.acmeWebroot}/.well-known/acme-challenge"
    <Directory "${input.acmeWebroot}/.well-known/acme-challenge">
        Require all granted
    </Directory>

    <Location "/.well-known/hostd/${input.token}">
        Header always set X-Hostd-Token "${input.token}"
        Redirect 204
    </Location>

    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\\.well-known/
    RewriteRule ^/?(.*)$ https://${input.primary}/$1 [R=301,L]
</VirtualHost>`
}

// The maintenance rules come before the proxy so that a deploy in progress, or an upstream that is not
// answering, both meet the holding page rather than a proxy error. ErrorDocument 503 is what turns a
// failed proxy into the same page, which is the half of this that covers an unplanned outage.
function port443(input: VhostInput): string {
    return `<VirtualHost *:443>
    ServerName ${input.primary}
${aliasLines(input.aliases)}

    SSLEngine on
    SSLCertificateFile ${input.certificate.chain}
    SSLCertificateKeyFile ${input.certificate.key}

    <Location "/.well-known/hostd/${input.token}">
        Header always set X-Hostd-Token "${input.token}"
        Redirect 204
    </Location>

    DocumentRoot "${input.maintenanceDir}"
    ErrorDocument 503 /index.html
    Header always set Retry-After "120" "expr=%{REQUEST_STATUS} == 503"

    RewriteEngine On
    RewriteCond expr -f "${input.maintenanceFlag}"
    RewriteRule ^ - [R=503,L]

    ProxyPreserveHost On
    ProxyPass /.well-known/hostd/${input.token} !
    ProxyPass / http://127.0.0.1:${input.port}/
    ProxyPassReverse / http://127.0.0.1:${input.port}/
</VirtualHost>`
}

// An alias never serves the site. It exists to send a visitor to the one canonical address, so that a
// site is not reachable at two URLs with two sets of cookies and two entries in a search index.
function aliasRedirect(input: VhostInput): string {
    if (input.aliases.length === 0) return ''
    return `
<VirtualHost *:443>
${input.aliases.map(alias => `    ServerName ${alias}`).join('\n')}

    SSLEngine on
    SSLCertificateFile ${input.certificate.chain}
    SSLCertificateKeyFile ${input.certificate.key}

    Redirect permanent / https://${input.primary}/
</VirtualHost>`
}

export function renderVhost(input: VhostInput): string {
    return `# Generated by hostd for ${input.id} (${input.environment}). Do not edit: every change hostd makes
# rewrites this file in full. To take a site back by hand, move this file out of the include directory.

${port80(input)}

${port443(input)}${aliasRedirect(input)}
`
}
