import { describe, it } from 'node:test'
import assert from 'node:assert/strict'

import { renderVhost, vhostPath, type VhostInput } from './vhost.ts'

const input = (over: Partial<VhostInput> = {}): VhostInput => ({
    id: 'acme',
    environment: 'live',
    primary: 'acme.com',
    aliases: ['www.acme.com'],
    port: 5010,
    token: 'abc123',
    certificate: { chain: '/etc/ssl/hostd/origin.pem', key: '/etc/ssl/hostd/origin.key' },
    maintenanceDir: '/var/www/hostd-maintenance',
    maintenanceFlag: '/run/hostd/maintenance/acme-live',
    acmeWebroot: '/var/www/hostd-acme',
    ...over,
})

describe('vhostPath', () => {
    it('names the file after the project and the environment', () => {
        assert.equal(vhostPath('/etc/apache2/hostd', 'acme', 'test'), '/etc/apache2/hostd/acme-test.conf')
    })
})

describe('renderVhost', () => {
    it('serves the primary and every alias on port 80', () => {
        const text = renderVhost(input())
        const port80 = text.split('<VirtualHost')[1] ?? ''
        assert.match(port80, /ServerName acme\.com/)
        assert.match(port80, /ServerAlias www\.acme\.com/)
    })

    it('serves the ACME challenge directory before redirecting, so a challenge is never 301ed away', () => {
        const text = renderVhost(input())
        const challenge = text.indexOf('/.well-known/acme-challenge')
        const redirect = text.indexOf('RewriteRule')
        assert.ok(challenge >= 0 && redirect > challenge, 'the challenge alias must come before the redirect')
    })

    it('answers the verification token with 204 and the token in a header', () => {
        const text = renderVhost(input({ token: 'deadbeef' }))
        assert.match(text, /<Location "\/\.well-known\/hostd\/deadbeef">/)
        assert.match(text, /Header always set X-Hostd-Token "deadbeef"/)
        assert.match(text, /Redirect 204/)
    })

    it('proxies the primary on 443 to the environment\'s own port', () => {
        assert.match(renderVhost(input({ port: 5108 })), /ProxyPass \/ http:\/\/127\.0\.0\.1:5108\//)
    })

    it('serves the holding page when the maintenance flag exists', () => {
        const text = renderVhost(input())
        assert.match(text, /RewriteCond expr "-f '\/run\/hostd\/maintenance\/acme-live'"/)
        assert.match(text, /ErrorDocument 503/)
    })

    it('redirects each alias to the primary on 443 rather than serving it', () => {
        const text = renderVhost(input())
        const aliasBlock = text.split('<VirtualHost').pop() ?? ''
        assert.match(aliasBlock, /ServerName www\.acme\.com/)
        assert.match(aliasBlock, /Redirect permanent \/ https:\/\/acme\.com\//)
        assert.doesNotMatch(aliasBlock, /ProxyPass/)
    })

    it('writes no alias virtual host at all when there are none', () => {
        const text = renderVhost(input({ aliases: [] }))
        assert.equal(text.match(/<VirtualHost/g)?.length, 2)
        assert.doesNotMatch(text, /Redirect permanent/)
    })

    it('names the certificate it was given and never interpolates anything else into an SSL directive', () => {
        const text = renderVhost(input())
        assert.match(text, /SSLCertificateFile \/etc\/ssl\/hostd\/origin\.pem/)
        assert.match(text, /SSLCertificateKeyFile \/etc\/ssl\/hostd\/origin\.key/)
    })

    it('says at the top that it is generated, so nobody edits it by hand', () => {
        assert.match(renderVhost(input()), /^# Generated by hostd/)
    })

    it('emits no JavaScript-style comment lines, which Apache would reject as unknown directives', () => {
        const text = renderVhost(input())
        for (const line of text.split('\n')) {
            assert.ok(!line.trim().startsWith('//'), `found a // line: ${line}`)
        }
    })

    it('declares only the primary in the primary 443 block, never an alias', () => {
        const text = renderVhost(input())
        const primaryBlock = text.split('<VirtualHost *:443>')[1]?.split('</VirtualHost>')[0] ?? ''
        assert.doesNotMatch(primaryBlock, /ServerAlias/)
    })

    it('never declares the same hostname in more than one 443 block, so every block stays reachable', () => {
        const text = renderVhost(input())
        const blocks = [...text.matchAll(/<VirtualHost \*:443>([\s\S]*?)<\/VirtualHost>/g)].map(match => match[1] ?? '')
        const blockCounts = new Map<string, number>()
        for (const block of blocks) {
            const names = new Set<string>()
            for (const line of block.split('\n')) {
                const match = line.match(/^\s*Server(?:Name|Alias)\s+(.+)$/)
                if (match) for (const name of match[1]!.trim().split(/\s+/)) names.add(name)
            }
            for (const name of names) blockCounts.set(name, (blockCounts.get(name) ?? 0) + 1)
        }
        for (const [name, count] of blockCounts) {
            assert.equal(count, 1, `${name} is declared in ${count} separate 443 blocks`)
        }
    })

    it('answers the verification token on the alias block before redirecting it away', () => {
        const text = renderVhost(input({ token: 'deadbeef' }))
        const aliasBlock = text.split('<VirtualHost').pop() ?? ''
        const location = aliasBlock.indexOf('<Location "/.well-known/hostd/deadbeef">')
        const redirect = aliasBlock.indexOf('Redirect permanent')
        assert.ok(location >= 0 && redirect > location, 'the token Location must come before the redirect')
    })
})
